### ISSUE TITLE
Create map page

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#12]
- [x] Create custom google map.
- [x] input site coordinates
- [ ] Assign to Kenni

**Comment by kennib** [comment]
Take a look at https://www.mapbox.com

**Comment by techieshark** [comment]
Draft map: https://www.google.com/maps/d/u/0/edit?mid=1SIhep-8GnWeSjMZvED0uGQI7DkQ
