### ISSUE TITLE
button text cut off in safari

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/heritage-near-me#125]
Looks like transparent border cuts off text in safari (desktop + mobile):

![image](https://cloud.githubusercontent.com/assets/1072292/18072838/c82f795c-6ea4-11e6-82da-d04a58dcf9a7.png)

@jessemoreburritos is on this I think.

**Comment by jessemoreburritos** [comment]
Done!

**Comment by techieshark** [comment]
closed by https://github.com/CodeforAustralia/heritage-near-me/commit/d234917f2cb372956813ef43b85faf72757bdee0
