### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#145]
-Need to rethink how stats are displayed on heritagenear.me/stats.html so that information is more practical. 
Something displaying stats and numbers more clearly and unified would be pretty useful.

**Comment by techieshark** [comment]
We might also want to wipe the stats just before user testing starts -- all the stats so far are from us, in development, and are therefore currently meaningless.

But in the interest of acquiring meaningful stats - we need to decide what those might be. @jessemoreburritos has a Google doc about that I think, and I have an evernote doc as well, but I don't recall if we decided on anything specific. (Plus, a bigger issue: unless we have a relatively large number of beta testers, I'm not sure analytics give us anything useful that we don't get from simple observation and questions during qualitative user testing.)
