### ISSUE TITLE
Create loading page

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#15]
- [ ] Create welcome/loading page to sketch file design
![screen shot 2016-02-10 at 3 42 31 pm](https://cloud.githubusercontent.com/assets/16284413/12938846/f86a575e-d00c-11e5-8943-4601b9a48b97.png)

**Comment by theatlasroom** [comment]
Is this still an open issue?

**Comment by techieshark** [comment]
@theatlasroom yeah. Perhaps could be implemented well with app cache and/or service workers. Updated loading screen looks like this:

<img width="284" alt="screen shot 2016-08-09 at 7 45 20 pm" src="https://cloud.githubusercontent.com/assets/1072292/17512174/f50949c6-5e69-11e6-92fb-dcd853505ace.png">
