### ISSUE TITLE
add end of story marker div #analytics

### ISSUE THREAD

**Issue by techieshark** [CodeforAustralia/heritage-near-me#153]
We want a div guaranteed to mark the end of the story's text so analytics can check if people actually get to the bottom of stories.

**Comment by jessemoreburritos** [comment]
Is this in the live version?

**Comment by more-like-a-puma** [comment]
It's only just been merged today, we need to update what is being hosted by digital ocean.

**Comment by techieshark** [comment]
@jessemoreburritos Yes, I merged all this into the `live` branch and the live site is running on the `live` branch rather than `master` (so that we could test things that need to be tested on the live site before merging into master, and since I wanted to let @more-like-a-puma double check it and merge to master). 

live site, inspected in chrome:

![image](https://cloud.githubusercontent.com/assets/1072292/18425090/a9e78232-78f9-11e6-93e0-b38155c8f906.png)
