### ISSUE TITLE
Wire framing and app/site navigation

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#30]
Refine & share for feedback

**Comment by techieshark** [comment]
@jessemoreburritos can you say what the status of this is? Still valid?  I'm uncertain what exactly needs to be done (you have wireframes and app/site nav flow chart I think, so I'm not sure if this was that or something else).

**Comment by jessemoreburritos** [comment]
This no longer applies. I have been using trello lately. I'll add you to
that board.
Apologies for the confusion

**Comment by techieshark** [comment]
Cool, closing this then.
