### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by crabmusket** [CodeforAustralia/heritage-near-me#55]
Code review 2016-3-10

**Comment by eightyeight** [comment]
What is `StartApp`.

**Comment by eightyeight** [comment]
Put modules into a `src`

**Comment by techieshark** [comment]
This is a great set of questions. I ran into the same, and to some extent have added documentation and links to the code itself. I'll also leave some answers here.

What is StartApp. How does it work?

A couple resources:
* http://package.elm-lang.org/packages/evancz/start-app/2.0.0/StartApp 
* https://yobriefca.se/blog/2015/08/02/deconstructing-your-first-elm-app/

What is a Mailbox? How does view get its Address?

* See this (https://medium.com/@diamondgfx/understanding-elm-signals-mailboxes-addresses-and-actions-7932781396ef#.cetz0xe2e)

* but know that those are going away in Elm 0.17: http://www.lambdacat.com/migrating-from-elm-0-16-to-0-17-from-startapp/

What is RouteHash? What does routeTasks do?

* http://package.elm-lang.org/packages/rgrempel/elm-route-hash/1.0.5/RouteHash

What are ports?

* They allow communication with Javascript: http://guide.elm-lang.org/interop/javascript.html

Which libraries are internal, which are external?

In the code, we usually put packaged modules first, followed by our custom code; here's an example from our file `App.elm`:

```
-- first let's import functions from some Elm library modules we'll need:
import Html exposing (Html)
import Time exposing (Time)
import Task exposing (Task)
import Json.Encode
...

-- and let's import some of our custom types and functions we'll need:
import Types exposing (..)
...
import Data
import View exposing (view)
import Story
```


Where are the types?

* `Types.elm`

What are Actions?

* See the medium article mentioned above and this one https://medium.com/@diamondgfx/working-with-elm-applying-signals-and-actions-to-our-app-e1c649bd0d96#.tbr0d8dzc

What is Location?

* The page / screen we're on.

favouriteItem and passItem are confusing.

* Yup. They'd be simpler if not for the need to handle `Loaded` vs unloaded items.

How does Discovery type work?

Where is the data? 

* Stored in Postgres, served as API by PostgREST, which Nginx redirects to if the URL has /api/ in it.



What is Remote.DataStore.fetch?
What generates an Action?
What are Effects. what are they for?
The remote data fetching effect is confusing.

* So confusing. I tried documenting it. https://github.com/CodeforAustralia/heritage-near-me/blob/master/prototype/src/App.elm#L369

How does the Task type work?
Remote.DataStore.fetch's alter is confusing.
updateStory is confusing. Maybe expand out the case to make things clearer.
Remote.Data.get has a confusing name. Maybe Remote.Data.toMaybe is better.
fetchDiscover is complicated. Particularly the function application and formatting choices.
Why is ItemPosition so complex?

**Comment by eightyeight** [comment]
Just to provide some context, this list came from Kenni and I sitting down and walking through the code while Kenni recorded my questions stream-of-consciousness style, and mostly answered them on the spot.

**Comment by techieshark** [comment]
@eightyeight thanks for the context. I had similar questions when I started looking at the code, and figure others might as well. Cheers!
