### ISSUE TITLE
Add user generated content to the database

### ISSUE THREAD

**Issue by kennib** [CodeforAustralia/heritage-near-me#58]
This content is currently submitted via a [Google form](https://drive.google.com/open?id=1JbLB9vdURgb02sYIE4y-fPwiQvtY1QluqSBaja591Uk) which stores the result in a [Google spreadsheet](https://drive.google.com/open?id=1M5akx0LmzGhtIATmEzQRs7TevutXx5B1uM1ZqwWBdYs).

My plan is to use [Google Apps Script](https://developers.google.com/apps-script/) to allow people with write access to the spreadsheet to submit content to the app.

This will be done using some simple HTTP requests to the Heritage Near Me Postgrest API.

**Comment by techieshark** [comment]
1b81a89f25eaba244e0fcf04b5b141a9058494b5 added some [ETL code](https://github.com/CodeforAustralia/heritage-near-me/tree/master/etl) to extract data from the spreadsheet, transform it to fit the database and use SQL to load it. This issue can be closed.
