### ISSUE TITLE
Fancy pants page loader 

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#59]
Can we use one of these loaders and scale it down to about 80%?
For what we're doing, i'm liking the last one on the fourth row down.

https://connoratherton.com/loaders
https://github.com/ConnorAtherton/loaders.css

**Comment by techieshark** [comment]
Hey @jessemoreburritos I'm not quite sure what this issue means. What are you referring to by "last one on the fourth row down"? 

Thanks!

**Comment by jessemoreburritos** [comment]
Haha oh sorry man.
This wasn't at all a priority, but i was just asking kenni if we could use
the preloader on that link... the animation in the 4th row on the far right.
On 16 Apr 2016 3:17 pm, "Peter W" <notifications@github.com> wrote:

Hey @jessemoreburritos <https://github.com/jessemoreburritos> I'm not quite
sure what this issue means. What are you referring to by "last one on the
fourth row down"?

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/CodeforAustralia/heritage-near-me/issues/59#issuecomment-210738577>

**Comment by jessemoreburritos** [comment]
Oh sheiße! I didnt realise indidnt include the github link!

**Comment by jessemoreburritos** [comment]
https://connoratherton.com/loaders
^This is what I was referring to.
https://github.com/ConnorAtherton/loaders.css

**Comment by techieshark** [comment]
+1 

I updated the description for this issue to clarify.
