### ISSUE TITLE
Create more info page

### ISSUE THREAD

**Issue by jessemoreburritos** [CodeforAustralia/heritage-near-me#79]
Need a more info page as per UI design.

![image](https://cloud.githubusercontent.com/assets/16284413/17233219/783766e0-5571-11e6-8ade-82942a8a70ca.png)

This section is just display what info we were given.
I trust this content will change significantly once we move off the project.

**Comment by techieshark** [comment]
todo: 
- [ ] Add More Info screen
- [ ] style More Info screen
- [ ] Add Heritage categories to screen
- [ ] Get links on more info screen, from database (current code just generates link using heritage id)

**Comment by techieshark** [comment]
Heritage categories and links aren't included in the story details API output yet -- I'll have to get to that before I can muck with elm more.
